//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUrun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUrun()
        {
            this.tblSatis = new HashSet<tblSatis>();
        }
    
        public int urunID { get; set; }
        public string urunAd { get; set; }
        public string marka { get; set; }
        public Nullable<short> stok { get; set; }
        public Nullable<decimal> fiyat { get; set; }
        public Nullable<bool> durum { get; set; }
        public Nullable<int> kategori { get; set; }
    
        public virtual tblKategori tblKategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSatis> tblSatis { get; set; }
    }
}
